---
name: 'Qwiet'
'on':
  pull_request: null
  workflow_dispatch: null
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  NextGen-Static-Analysis:
    runs-on: 'windows-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Set up .NET'
        uses: 'actions/setup-dotnet@v1'
        with:
          dotnet-version: '5.0.x'
      - name: 'Download Qwiet CLI'
        run: "Invoke-WebRequest -Uri 'https://cdn.shiftleft.io/download/sl-latest-windows-x64.zip' -OutFile sl.zip\nExpand-Archive -Path sl.zip -DestinationPath . -Force\n"
      - name: 'Analyze with NextGen Static Analysis'
        run: '.\sl analyze --strict --app eShopOnWeb --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --csharp --dotnet balapoll/eShopOnWeb/src/ApplicationCore/ApplicationCore.csproj'
        env:
          SHIFTLEFT_ACCESS_TOKEN: '${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}'
